---

- name: Create configuration dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ certmgr_user }}"
    group: "{{ certmgr_group }}"
  with_items:
    - "{{ certmgr_configdir }}"
    - "{{ certmgr_cert_configdir }}"

- name: Setup configuration
  template:
    src: certmgr.yaml.j2
    dest: "{{ certmgr_configdir }}/certmgr.yaml"
    owner: "{{ certmgr_user }}"
    group: "{{ certmgr_group }}"
    mode: 0644
  notify: restart certmgr

- name: Add certificate definitions
  template:
    src: cert.json.j2
    dest: "{{ certmgr_cert_configdir}}/{{ item.name }}.json"
    owner: "{{ certmgr_user }}"
    group: "{{ certmgr_group }}"
    mode: 0600
  with_items: "{{ certmgr_cert_defs }}"
  notify: restart certmgr

- block:
    - name: Create certificate groups
      group:
        name: "{{ item.private_key_group }}"
      when: item.private_key_group is defined
      loop: "{{ certmgr_cert_defs }}"

    - name: Create certificate users
      user:
        name: "{{ item.private_key_owner }}"
        groups: "{{ item.private_key_group }}"
      when: item.private_key_owner is defined
      loop: "{{ certmgr_cert_defs }}"
  when: certmgr_manage_users_and_groups

- block:
    - name: Extract certificates paths
      set_fact: certmgr_certs_paths="{{ item.0[item.1] | dirname }}"
      loop: "{{ certmgr_cert_defs | product(['private_key_path', 'certificate_path', 'authority_path']) | list }}"
      register: certmgr_certs_paths_results

    - name: Create certificates directories
      file:
        path: "{{ item }}"
        state: directory
      loop: "{{ certmgr_certs_paths_results.results | map(attribute='ansible_facts.certmgr_certs_paths') | list | unique }}"
  when: certmgr_manage_cert_dirs

- name: Download CA certificate from every remote configured
  shell: curl -X POST -d '{"label":"","profile":"{{ item.authority_profile }}"}' -sk \
         {{ item.authority_remote }}/api/v1/cfssl/info | jq -r '.result.certificate' >  {{ item.name }}.pem
  args:
    chdir: /etc/ssl/certs/
  become: true
  become_user: "{{ certmgr_user }}"
  with_items: "{{ certmgr_cert_defs }}"
  notify: restart certmgr
  when: item.authority_remote is search('https://')
  failed_when: False

- name: CertMgr clean certificates
  command: certmgr clean
  become: true
  become_user: "{{ certmgr_user }}"
  failed_when: False
  when: certmgr_clean | bool

- name: CertMgr first run
  command: certmgr ensure
  become: true
  become_user: "{{ certmgr_user }}"
  failed_when: False
