---

- name: restart certmgr
  service:
    state: restarted
    name: certmgr
  when: certmgr_service_state == "started"

- name: start certmgr
  service:
    state: started
    name: certmgr
  when: certmgr_service_state == "started"
